# Setup
title:               Swaathi Kakarla
name:                Swaathi
tagline:             Usually about code, but not always
description:         'Empathetic human being who loves to code, read, and wonder about the universe. Living the dream at <a href="https://www.skcript.com">Skcript</a> where we build
<a href="https://www.skcript.com/shrink">Shrink</a> and <a href="https://allt.in">Allt</a>.'

enforce_ssl:         true
url:                 www.swaathi.com
# url:                 localhost:4000

paginate:            5

github:
  repo:              https://github.com/swaathi

twitter:
  username: imswaathik

google_analytics:
  token:             UA-80560343-1

skcript:
  main:              https://www.skcript.com
  blog:              https://blog.skcript.com
  shrink:            https://www.skcript.com/shrink
  allt:              https://allt.in

# About/contact
author:
  name:              Swaathi Kakarla
  twitter:           https://twitter.com/imswaathik
  email:             swaathi@skcript.com

# Permalinks
permalink:           pretty

# Custom vars
version:             1.0.0
